import { AppProps } from "next/app";
import "../styles/globals.css";
import Head from "next/head";
import React from "react";

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
    return <>
        <Head>
            <title>My Top</title>
            <meta name="description" content="Generated by create next app" />
            <link key={1} rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link
                href="https://fonts.googleapis.com/css2?family=Noto+Sans+Display:wght@300;400;500;700&family=Roboto:wght@500&display=swap"
                rel="stylesheet"
            />
        </Head>
        <Component {...pageProps} />
    </>;
}

export default MyApp;